swiftmailer:
    default_mailer: default
    mailers:
        default:
            spool:
                type: memory
                path: /home/cubias/workspace/htdocs/ssamanes/var/cache/dev/swiftmailer/spool
                id: null
            transport: smtp
            command: '/usr/sbin/sendmail -bs'
            username: '%env(MAILER_USER)%'
            password: '%env(MAILER_PWD)%'
            host: smtp.gmail.com
            timeout: 30
            encryption: ssl
            logging: true