monolog:
    handlers:
        main:
            type:         fingers_crossed
            # 500 errors are logged at the critical level
            action_level: critical
            handler:      grouped
        grouped:
            type:    group
            members: [streamed, deduplicated]
        streamed:
            type:  stream
            path:  '%kernel.logs_dir%/%kernel.environment%.logg'
            level: debug
        deduplicated:
            type:    deduplication
            # the time in seconds during which duplicate entries are discarded (default: 60)
            time: 30
            handler: swift
        swift:
            type:       swift_mailer
            from_email: 'mccubo.spam@gmail.com'
            to_email:   ['mccubopsn@gmail.com']
            subject:    'SSAMANES DB: An Error Occurred! %%message%%'
            level:      debug
            formatter:  monolog.formatter.html
            content_type: text/html